export const heroBannerStyles = {
  contentStyle: {
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-between',
    minHeight: '300px',
    width: '100%',
    margin: '0px',
    padding: '0px',
    outline: 'none',
    borderRadius: '0px',
  },
  cardStyle: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#00000069',
    opacity: '0.99',
    color: 'common.black',
    justifyContent: 'center',
    width: { xs: '100%', md: '100%' },
    height: '100%',
    gap: 2,
    paddingLeft: '5%',
    paddingRight: '5%',
  },
  cardStyleMobile: {
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#00000069',
    opacity: '0.99',
    color: 'common.black',
    justifyContent: 'center',
    width: { xs: '100%', md: '100%' },
    height: '100%',
    gap: 2,
    paddingLeft: '5%',
    paddingRight: '5%',
    alignItems: 'center',
  },
  titleStyle: {
    fontWeight: '700',
    fontSize: '2.5rem',
    maxWidth: '50%',
    lineHeight: '95%',
    color: 'white',
  },
  titleStyleMobile: {
    fontWeight: '700',
    fontSize: '2rem',
    lineHeight: '95%',
    color: 'white',
    textAlign: 'center',
  },
  subtitleStyle: {
    fontWeight: '500',
    fontSize: '1.1rem',
    color: 'white',
  },
  subtitleStyleMobile: {
    fontWeight: '400',
    fontSize: '1rem',
    color: 'white',
    textAlign: 'center',
  },
}
